### ISSUE TITLE
Code chunk formatting problem

### ISSUE THREAD

**Issue by hpages** [The-Sequence-Ontology/Specifications#11]
Note that there is a formatting problem in the last line of the 3rd code chunk of the _**Trans-spliced transcript**_ section:
```
chrX  . exon               XXXX YYYY  .  +  . Parent=tran01 chrX . CDS XXXX YYYY . + . ID=cds01;Parent=tran01
```
Looks like 2 lines (exon and CDS) have been concatenated together:

Thanks!

**Comment by alexhenrie** [comment]
You were absolutely right. Thanks for reporting this, I have fixed the formatting in that example.

**Comment by hpages** [comment]
Thanks! Looks like a small indentation problem remains though.

**Comment by alexhenrie** [comment]
Sorry I overlooked that. The spacing is fixed now too.

**Comment by hpages** [comment]
Are you sure? The` XXXX` `YYYY` fields are not aligned. Thanks!

**Comment by alexhenrie** [comment]
Sorry again. I guess third time's the charm.

**Comment by hpages** [comment]
Looks good now. Thanks!
